# Generated by Django 5.0.2 on 2024-06-03 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_habit_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habit')),
            ],
        ),
    ]
