# Generated by Django 5.0.2 on 2024-06-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_habit_completed_remove_habit_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
