# Generated by Django 5.1 on 2024-08-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_habitcompletion_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitcompletion',
            old_name='count',
            new_name='completed_count',
        ),
    ]
