# Generated by Django 5.1 on 2024-08-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_count_habitcompletion_completed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HabitCompletion',
        ),
    ]
